version: '3.7'
services:
  api:
    build: api/.
    environment:
      - DBURL=postgres://postgres:testing@db:5432/postgres
    ports:
      - "8080:8080"
    depends_on:
      - db
  db:
    image: postgres:12-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=testing
    ports:
      - '5432:5432'
    volumes:
      - db-data:/var/lib/financeview/dbdata
      - ./sql/ddl/create_schema.sql:/docker-entrypoint-initdb.d/create_schema.sql

volumes:
  db-data: