version: '3.7'
services:
  postgres:
    image: postgres:12-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=testing
    ports:
      - '5432:5432'
    volumes:
      - db-data:/var/lib/financeview/testdbdata
      - ./sql/ddl/create_schema.sql:/docker-entrypoint-initdb.d/create_schema.sql

volumes:
  db-data: