// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type NewExpense struct {
	Date        string   `json:"date"`
	Description string   `json:"description"`
	Amount      float64  `json:"amount"`
	Categories  []string `json:"categories"`
	Comment     *string  `json:"comment"`
}
